### ISSUE TITLE
Trim doesn't work when start time is 0

### ISSUE THREAD

**Issue by gilesbennett** [falahati/PHP-MP3#1]
Trying to get the first 30 seconds of a file to a new file : 

$this->removeFrame($endIndex, $this->getFrameCounts() - $endIndex);

works fine, but 

$this->removeFrame(0, $startIndex);

results in 

Fatal error: Uncaught Error: Call to a member function getOffset() on boolean in /home/forge/simytmt.com/public/vendor/falahati/php-mp3/src/MpegAudio.php:406

**Comment by falahati** [comment]
Please try the latest commit and report back if it fails.

Thanks

**Comment by gilesbennett** [comment]
Seems to have done the trick, thank you.

Kind regards,

Giles

Kind regards,

Giles

Giles Bennett / Founder
+44 (0)7766 687 658 / giles@hummingbirduk.com
<http://www.hummingbirduk.com>

Hummingbird UK Web Design Ltd.

+44 (0)113 314 8664
U
<https://maps.google.co.uk/maps?q=yo8+4nj&hnear=Selby+YO8+4NJ,+United+Kingdom&t=m&z=16>nit
10, Blackwood Hall Business Park, Cornelius Causeway, North Duffield, North
Yorkshire, YO8 5DD

www.hummingbirduk.com
This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Hummingbird UK is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.
Hummingbird UK is the trading name of Hummingbird UK Web Design Limited, a
company registered in England and Wales under company number 08723764.
