### ISSUE TITLE
Is it possible to trim other format of audio ?

### ISSUE THREAD

**Issue by MushfiqueAhmed027** [falahati/PHP-MP3#10]
Can't trim other formats of audio except for mp3.Is It possible to cut any format of audio?

**Comment by amir-habibi-dev** [comment]
i am going to use it, then i will inform you

**Comment by falahati** [comment]
no it is not. this is a MPEG4 parser. MPEG4 is a container, it doesn't matter what is stored inside of it. You can use it to trim other codecs of audio as long as it is stored in a MPEG4 container. otherwise, it can not parse any other container.
