### ISSUE TITLE
Trimming audio is not working

### ISSUE THREAD

**Issue by 3gHub** [falahati/PHP-MP3#11]
`$mp3 = \falahati\PHPMP3\MpegAudio::fromFile($request->song)->trim(1, 30)->saveFile(storage_path('app/public/PreviewSong').'/new.mp3');`

I am using the above code to trim audio but trim is now working. The whole audio file saved to the destination. Kindly help ASAP @falahati

**Comment by 3gHub** [comment]
@falahati My file is **.mp3** but still it is not working. 

`getFrameCounts()` returns `0` and `getFrameHeader(0)` returns false here.

I have tried with many **.mp3** files but I don't know the reason.

**Comment by falahati** [comment]
Can you send me a couple of these files to test?

**Comment by 3gHub** [comment]
Sure I am sending mp3 files. Within some minutes. Can you give me your email ? Because `.mp3` is not supported here.

**Comment by falahati** [comment]
sure, s_falahati@hotmail.com
you can also upload them to google drive or some other cloud service and post the URL here

**Comment by 3gHub** [comment]
I have sent 2 mp3 files via email. Kindly check.

**Comment by falahati** [comment]
check out the latest commit. should work

**Comment by 3gHub** [comment]
Will I run `Composer Update` ?

**Comment by 3gHub** [comment]
Yes It is Working now. Thanks @falahati.

I have one small question though. Which file extension does this support. only `.mp3`  or any other ?

**Comment by falahati** [comment]
It doesn't care about the file extension, it does support the MPEG Audio Version 1, 2 and 2.5
