### ISSUE TITLE
Removal of ID3 metadata information

### ISSUE THREAD

**Issue by dasj19** [falahati/PHP-MP3#4]
Hello, First of all great job with this project.

I wonder if it is possible to remove existing ID3 metadata information from the resulting file.
I noticed that it keeps the metadata of the last file when I join multiple files.
My code is something like this:
```
$mpeg_audio = new MpegAudio();
foreach ($files as $file_path) {
  $mpeg_audio->append($mpeg_audio->fromFile($file_path));
}
$mpeg_audio->saveFile($final_path);
```

**Comment by falahati** [comment]
There is a function exactly for that in the library:

```PHP
$mpeg_audio = new MpegAudio();
foreach ($files as $file_path) {
  $newMpegWithoutTags = $mpeg_audio->fromFile($file_path)->stripTags();
  $mpeg_audio->append($newMpegWithoutTags);
}
$mpeg_audio->saveFile($final_path);
```

**Comment by dasj19** [comment]
hi @falahati thanks for provided input.
I have 2 remarks to make.
1. stripTags() does not seem to work on the mp3 files I feed to the PHP-MP3 library
2. If I append audio files in a foreach as suggested above, the output comes in reverse order... so I have to do `foreach(array_reverse($files) as $file_path)`. Is there a reason for this behavior?

**Comment by falahati** [comment]
`stripTags()` removes anything that is not a MPEG audio frame from the end and the start of the file. If your MP3 files are still messy; maybe it contains tags in the middle of the file which is unusual but might happen if you created the MP3 files by appending them like a file and not using a proper tool for that.

That being said; even calling `append()` alone will ignore the tags in the file.

Please post your full code so I can take another look into it. Maybe even put some sample MP3 files next to it so I can test the behaviour of the code in regard to those files.

`append()` always adds the new MP3 file to the end of the stream. 

If the order is incorrect; you need to sort them before appending to the stream. This depends on the way you gathered the list of files. For example, if using `readdir()` to get the file list, the return value is sorted by the file system creation date and therefore you need to sort it again by which order you prefer. Following code orders the files alphabetically:

```PHP
natsort($file_path);
```

**Comment by dasj19** [comment]
thanks a lot for getting back... you are right about tags in the middle of the file.. now I changed my code to strip tags on all calls to fromFile() function... and the resulting mp3 has every tags removed.

now... about the ordering... I have an array of filepaths which is manually ordered (by the user)  and when I run on the files and append them one by one ... they allways come out in the reverse order (have only tried with as much as 3 files until now)

**Comment by falahati** [comment]
Happy you found the problem.

In regard to ordering; `append()` always adds the new stream to the end of the current stream; in any case tho; if it always comes out reversed you can probably simply reverse the file name array.
