### ISSUE TITLE
Fade in and out volume when cutting mp3

### ISSUE THREAD

**Issue by sixtyseven-multimedia** [falahati/PHP-MP3#9]
I really like your class and I use it to create preview files from my band's mp3 on our homepage. Could you probably enhance the class to change the volume, like a fade in / fade out?

Would make this even more useful for us musicians!

**Comment by falahati** [comment]
unfortunately modifying the audio itself requires decoding and encoding of the audio file. this library is just a MPEG parser and doesn't know how to recode a file. for that, you need to use a more sophisticated tool like FFMPEG which might bring more complications with itself.
this library was meant to be used as a light and fast way to create small preview files from longer files without actually recording the audio or changing the format.

there is one more way tho, if you are playing the audio on your website, you can always have a javascript code that fades the volume in and out after starting to play the audio and right before it ends. should provide you with the same effect without requiring additional work on the server side.
